#include <cstddef>

extern char _binary___Resources_Images_Introduction_introduction0_png_start;
extern char _binary___Resources_Images_Introduction_introduction0_png_end;
static const char* introductiion0 = &_binary___Resources_Images_Introduction_introduction0_png_start;
static const size_t introductiion0_size = &_binary___Resources_Images_Introduction_introduction0_png_end - &_binary___Resources_Images_Introduction_introduction0_png_start;

extern char _binary___Resources_Images_Introduction_introduction1_png_start;
extern char _binary___Resources_Images_Introduction_introduction1_png_end;
static const char* introductiion1 = &_binary___Resources_Images_Introduction_introduction1_png_start;
static const size_t introductiion1_size = &_binary___Resources_Images_Introduction_introduction1_png_end - &_binary___Resources_Images_Introduction_introduction1_png_start;

extern char _binary___Resources_Images_Introduction_introduction2_png_start;
extern char _binary___Resources_Images_Introduction_introduction2_png_end;
static const char* introductiion2 = &_binary___Resources_Images_Introduction_introduction2_png_start;
static const size_t introductiion2_size = &_binary___Resources_Images_Introduction_introduction2_png_end - &_binary___Resources_Images_Introduction_introduction2_png_start;
