name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Обновляем APT и устанавливаем зависимости SFML и инструменты сборки
      - name: Install SFML and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsfml-dev

      # 3. Показываем информацию о версии компилятора (опционально)
      - name: Show compiler version
        run: |
          g++ --version
          make --version

      # 4. Запускаем сборку через Makefile
      - name: Build with Make
        run: |
          make

      # 6. Сохраняем собранный артефакт для последующего использования
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sfml-app
          path: build/GolubRun  # замените на имя вашего бинарника
