name: Build Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SFML and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsfml-dev

      - name: Show compiler version
        run: |
          g++ --version
          make --version

      - name: Build with Make
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GolubRun
          path: GolubRun
